-- RegisterNetEvent('qb-usable-accessories:client:TheftShoe', function()
--     local ped = PlayerPedId()
--     if not IsPedRagdoll(ped) then
--         local player, distance = QBCore.Functions.GetClosestPlayer()
--         if player ~= -1 and distance < 1.5 then
--             local playerId = GetPlayerServerId(player)
--             if not IsPedInAnyVehicle(GetPlayerPed(player)) and not IsPedInAnyVehicle(ped) then
--                 local oped = GetPlayerPed(player)
--                 local hasShoes = GetPedDrawableVariation(oped, 6)
--                 if hasShoes ~= 45 then
--                     while not HasAnimDictLoaded("random@domestic") do
--                         RequestAnimDict("random@domestic")
--                         Wait(1)
--                     end
--                     TaskPlayAnim(ped, "random@domestic", "pickup_low", 8.00, -8.00, 500, 0, 0.00, 0, 0, 0)
--                     TriggerServerEvent("qb-usable-accessories:server:TheftShoe", playerId)
--                     SetPedComponentVariation(oped, 6, 45, 0, 2)
--                 else
--                     QBCore.Functions.Notify("No shoes to been stolen!", "error")
--                 end
--             else
--                 QBCore.Functions.Notify('You can\'t steal shoes in vehicle', "error")
--             end
--         else
--             QBCore.Functions.Notify('No one nearby!', "error")
--         end
--     end
-- end)

-- RegisterNetEvent('qb-usable-accessories:client:StoleShoe', function(playerId)
--     local ped = PlayerPedId()
--     local hasShoes = GetPedDrawableVariation(ped, 6)
--     if hasShoes ~= 45 then
--         SetPedComponentVariation(ped, 6, 45, 0, 2)
--         QBCore.Functions.Notify("Shoes got robbed lmao", 'primary')
--         TriggerServerEvent("qb-usable-accessories:server:ShoeComplete", playerId)
--     else
--         QBCore.Functions.Notify("Someone tried to steal yo feet", 'primary')
--     end
-- end)